import {
  influenceClan1Image,
  influenceClan1ImageWebp,
  influenceClan2Image,
  influenceClan2ImageWebp,
  influenceClan3Image,
  influenceClan3ImageWebp,
  influenceClan4Image,
  influenceClan4ImageWebp,
  influenceClan5Image,
  influenceClan5ImageWebp,
  influenceClan6Image,
  influenceClan6ImageWebp,
  influenceClan7Image,
  influenceClan7ImageWebp,
  influenceClan8Image,
  influenceClan8ImageWebp,
  influenceClan9Image,
  influenceClan9ImageWebp,
  influenceClan10Image,
  influenceClan10ImageWebp,
  influenceClan11Image,
  influenceClan11ImageWebp,
  influenceClan12Image,
  influenceClan12ImageWebp,
  influenceClan13Image,
  influenceClan13ImageWebp,
  influenceClan14Image,
  influenceClan14ImageWebp,
  influenceClan15Image,
  influenceClan15ImageWebp,
  influenceClan16Image,
  influenceClan16ImageWebp,
  influenceClan17Image,
  influenceClan17ImageWebp,
  influenceClan18Image,
  influenceClan18ImageWebp,
  influenceClan19Image,
  influenceClan19ImageWebp,
  influenceClan20Image,
  influenceClan20ImageWebp,
  influenceClan21Image,
  influenceClan21ImageWebp,
  influenceClan22Image,
  influenceClan22ImageWebp,
  influenceClan23Image,
  influenceClan23ImageWebp,
  influenceClan24Image,
  influenceClan24ImageWebp,
  influenceClan25Image,
  influenceClan25ImageWebp,
  influenceClan26Image,
  influenceClan26ImageWebp,
  influenceClan27Image,
  influenceClan27ImageWebp,
  influenceClan28Image,
  influenceClan28ImageWebp,
  influenceClan29Image,
  influenceClan29ImageWebp,
  influenceClan30Image,
  influenceClan30ImageWebp,
  influenceClan31Image,
  influenceClan31ImageWebp,
  influenceClan32Image,
  influenceClan32ImageWebp,
  influenceClan33Image,
  influenceClan33ImageWebp,
  influenceClan34Image,
  influenceClan34ImageWebp,
  influenceClan35Image,
  influenceClan35ImageWebp,
  influenceClan36Image,
  influenceClan36ImageWebp,
  influenceClan37Image,
  influenceClan37ImageWebp,
  influenceClan38Image,
  influenceClan38ImageWebp,
  influenceClan39Image,
  influenceClan39ImageWebp,
  influenceClan40Image,
  influenceClan40ImageWebp,
  influenceClan41Image,
  influenceClan41ImageWebp,
  influenceClan42Image,
  influenceClan42ImageWebp,
  influenceClan43Image,
  influenceClan43ImageWebp,
  influenceClan44Image,
  influenceClan44ImageWebp,
  influenceClan45Image,
  influenceClan45ImageWebp,
  influenceClan46Image,
  influenceClan46ImageWebp,
  influenceClan47Image,
  influenceClan47ImageWebp,
} from "../../assets/imageMaps";

export const INFLUENCE_CLAN_EMBLEMS: {
  [key in string]: {
    src: string;
    srcSet: string;
    premium?: boolean;
  };
} = {
  clan1: {
    src: influenceClan1Image,
    srcSet: influenceClan1ImageWebp,
  },
  clan2: {
    src: influenceClan2Image,
    srcSet: influenceClan2ImageWebp,
  },
  clan3: {
    src: influenceClan3Image,
    srcSet: influenceClan3ImageWebp,
  },
  clan4: {
    src: influenceClan4Image,
    srcSet: influenceClan4ImageWebp,
  },
  clan5: {
    src: influenceClan5Image,
    srcSet: influenceClan5ImageWebp,
  },
  clan6: {
    src: influenceClan6Image,
    srcSet: influenceClan6ImageWebp,
  },
  clan7: {
    src: influenceClan7Image,
    srcSet: influenceClan7ImageWebp,
  },
  clan8: {
    src: influenceClan8Image,
    srcSet: influenceClan8ImageWebp,
  },
  clan9: {
    src: influenceClan9Image,
    srcSet: influenceClan9ImageWebp,
  },
  clan10: {
    src: influenceClan10Image,
    srcSet: influenceClan10ImageWebp,
  },
  clan11: {
    src: influenceClan11Image,
    srcSet: influenceClan11ImageWebp,
  },
  clan12: {
    src: influenceClan12Image,
    srcSet: influenceClan12ImageWebp,
  },
  clan13: {
    src: influenceClan13Image,
    srcSet: influenceClan13ImageWebp,
  },
  clan14: {
    src: influenceClan14Image,
    srcSet: influenceClan14ImageWebp,
  },
  clan15: {
    src: influenceClan15Image,
    srcSet: influenceClan15ImageWebp,
  },
  clan16: {
    src: influenceClan16Image,
    srcSet: influenceClan16ImageWebp,
  },
  clan17: {
    src: influenceClan17Image,
    srcSet: influenceClan17ImageWebp,
  },
  clan18: {
    src: influenceClan18Image,
    srcSet: influenceClan18ImageWebp,
  },
  clan19: {
    src: influenceClan19Image,
    srcSet: influenceClan19ImageWebp,
  },
  clan20: {
    src: influenceClan20Image,
    srcSet: influenceClan20ImageWebp,
  },
  clan21: {
    src: influenceClan21Image,
    srcSet: influenceClan21ImageWebp,
  },
  clan22: {
    src: influenceClan22Image,
    srcSet: influenceClan22ImageWebp,
  },
  clan23: {
    src: influenceClan23Image,
    srcSet: influenceClan23ImageWebp,
  },
  clan24: {
    src: influenceClan24Image,
    srcSet: influenceClan24ImageWebp,
  },
  clan25: {
    src: influenceClan25Image,
    srcSet: influenceClan25ImageWebp,
  },
  clan26: {
    src: influenceClan26Image,
    srcSet: influenceClan26ImageWebp,
  },
  clan27: {
    src: influenceClan27Image,
    srcSet: influenceClan27ImageWebp,
  },
  clan28: {
    src: influenceClan28Image,
    srcSet: influenceClan28ImageWebp,
  },
  clan29: {
    src: influenceClan29Image,
    srcSet: influenceClan29ImageWebp,
  },
  clan30: {
    src: influenceClan30Image,
    srcSet: influenceClan30ImageWebp,
  },
  clan31: {
    src: influenceClan31Image,
    srcSet: influenceClan31ImageWebp,
    premium: true,
  },
  clan32: {
    src: influenceClan32Image,
    srcSet: influenceClan32ImageWebp,
    premium: true,
  },
  clan33: {
    src: influenceClan33Image,
    srcSet: influenceClan33ImageWebp,
    premium: true,
  },
  clan34: {
    src: influenceClan34Image,
    srcSet: influenceClan34ImageWebp,
    premium: true,
  },
  clan35: {
    src: influenceClan35Image,
    srcSet: influenceClan35ImageWebp,
    premium: true,
  },
  clan36: {
    src: influenceClan36Image,
    srcSet: influenceClan36ImageWebp,
    premium: true,
  },
  clan37: {
    src: influenceClan37Image,
    srcSet: influenceClan37ImageWebp,
    premium: true,
  },
  clan38: {
    src: influenceClan38Image,
    srcSet: influenceClan38ImageWebp,
    premium: true,
  },
  clan39: {
    src: influenceClan39Image,
    srcSet: influenceClan39ImageWebp,
    premium: true,
  },
  clan40: {
    src: influenceClan40Image,
    srcSet: influenceClan40ImageWebp,
    premium: true,
  },
  clan41: {
    src: influenceClan41Image,
    srcSet: influenceClan41ImageWebp,
    premium: true,
  },
  clan42: {
    src: influenceClan42Image,
    srcSet: influenceClan42ImageWebp,
    premium: true,
  },
  clan43: {
    src: influenceClan43Image,
    srcSet: influenceClan43ImageWebp,
    premium: true,
  },
  clan44: {
    src: influenceClan44Image,
    srcSet: influenceClan44ImageWebp,
    premium: true,
  },
  clan45: {
    src: influenceClan45Image,
    srcSet: influenceClan45ImageWebp,
    premium: true,
  },
  clan46: {
    src: influenceClan46Image,
    srcSet: influenceClan46ImageWebp,
    premium: true,
  },
  clan47: {
    src: influenceClan47Image,
    srcSet: influenceClan47ImageWebp,
    premium: true,
  },
};
