import { ELanguages } from "../constants/ELanguages";
import { IIncluenceClan } from "../models/Influence/IIncluenceClan";

export const influenceClans: IIncluenceClan[] = [
  {
    id: "1",
    emblem: "clan1",
    name: "ГИЛДИЯ ОКУПАНТОВ",
    level: 3,
    members: 45,
    maxMembers: 50,
    language: ELanguages.ru,
    type: "public",
    description: "Элитный клан опытных бойцов в киберпанк мире",
  },
  {
    id: "2",
    emblem: "clan2",
    name: "Тень Протокола",
    level: 2,
    members: 50,
    maxMembers: 60,
    language: ELanguages.ru,
    type: "public",
    description: "Дружелюбное сообщество для игроков всех уровней",
  },
  {
    id: "3",
    emblem: "clan3",
    name: "Black Resonance",
    level: 5,
    members: 30,
    maxMembers: 55,
    language: ELanguages.en,
    type: "private",
    description: "Aggressive tactics, high rewards",
  },
  {
    id: "4",
    emblem: "clan4",
    name: "Ash Syndicate",
    level: 3,
    members: 36,
    maxMembers: 40,
    language: ELanguages.en,
    type: "private",
    description: "Elite international organization",
  },
  {
    id: "5",
    emblem: "clan5",
    name: "Звено 404",
    level: 3,
    members: 45,
    maxMembers: 60,
    language: ELanguages.ru,
    type: "public",
    description:
      "Молодой клан с большими амбициями. Ищем активных игроков для роста и развития.",
  },
  {
    id: "6",
    emblem: "clan6",
    name: "братство NOD",
    level: 3,
    members: 45,
    maxMembers: 60,
    language: ELanguages.ru,
    type: "public",
    description: "Ужасающий орден жрецов-воинов Братства",
  },
];
